### PR TITLE
Add command option «--no-suffix» for do not add suffix for test suites with duplicate names

### PR DESCRIPTION
**Pull request by sakharovmaksim**
Good afternoon!
After the pull-request #5 we ran into the problem that our CI Bamboo started displaying tests results incorrectly. We began to receive incorrect test names (see on screenshot).
xmlmergeproblem

### CODE REVIEW

**Comment by sakharovmaksim** [comment]
About PHP 5.3 on Travis CI: «Note: We do not support PHP versions 5.2.x and 5.3.x on Trusty. Specifying it will result in build failure. If you need to test with these versions, use Precise.»

**Comment by sakharovmaksim** [comment]
UP! Waiting for maintainer of repository.

**Comment by sakharovmaksim** [comment]
Up!

**Comment by andreaskweber** [comment]
Sorry for the delay! Thanks for your help! Enjoy your holidays! 😃

**Comment by andreaskweber** [comment]
Added version tag 1.0.5

**Pull request merged**
